rules:
  master:
    level: failure  # default rules are set to warning
  slave:
    level: failure
  blacklist:
    level: failure
  whitelist:
    level: failure
ignore:
 - ".github/in-solidarity.yml"  # default
 - ".github/workflows/*.yml"
 - "**/*.yml"
 - ".release-it.json"
 - "ocp_resources/grafana*"  # TODO: Remove when updated upstream https://github.com/grafana-operator/grafana-operator/issues/898
 - "ocp_resources/rhmi*"
