DEPLOYMENT_RES = {
    "BASE_CLASS": "NamespacedResource",
    "API_LINK": "https://example.explain",
    "GROUP": "apps",
    "KIND": "Deployment",
    "VERSION": "v1",
    "DESCRIPTION": "Deployment enables declarative updates for Pods and ReplicaSets.",
    "SPEC": [
        {
            "name-from-explain": "minReadySeconds",
            "name-for-class-arg": "min_ready_seconds",
            "type-for-class-arg": "min_ready_seconds: Optional[int] = None",
            "required": False,
            "type": "int",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "paused",
            "name-for-class-arg": "paused",
            "type-for-class-arg": "paused: Optional[bool] = None",
            "required": False,
            "type": "bool",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "progressDeadlineSeconds",
            "name-for-class-arg": "progress_deadline_seconds",
            "type-for-class-arg": "progress_deadline_seconds: Optional[int] = None",
            "required": False,
            "type": "int",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "replicas",
            "name-for-class-arg": "replicas",
            "type-for-class-arg": "replicas: Optional[int] = None",
            "required": False,
            "type": "int",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "revisionHistoryLimit",
            "name-for-class-arg": "revision_history_limit",
            "type-for-class-arg": "revision_history_limit: Optional[int] = None",
            "required": False,
            "type": "int",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "selector",
            "name-for-class-arg": "selector",
            "type-for-class-arg": "selector: Optional[Dict[str, Any]] = None",
            "required": True,
            "type": "Dict[Any, Any]",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "strategy",
            "name-for-class-arg": "strategy",
            "type-for-class-arg": "strategy: Optional[Dict[str, Any]] = None",
            "required": False,
            "type": "Dict[Any, Any]",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "template",
            "name-for-class-arg": "template",
            "type-for-class-arg": "template: Optional[Dict[str, Any]] = None",
            "required": True,
            "type": "Dict[Any, Any]",
            "description": "<please add description>",
        },
    ],
    "FIELDS": [],
}
