SECRET_RES = {
    "BASE_CLASS": "NamespacedResource",
    "API_LINK": "https://example.explain",
    "KIND": "Secret",
    "VERSION": "v1",
    "DESCRIPTION": "Secret holds secret data of a certain type. The total bytes of the values in\n    the Data field must be less than MaxSecretSize bytes.",
    "SPEC": [],
    "FIELDS": [
        {
            "name-from-explain": "data",
            "name-for-class-arg": "data",
            "type-for-class-arg": "data: Optional[Dict[str, Any]] = None",
            "required": False,
            "type": "Dict[Any, Any]",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "immutable",
            "name-for-class-arg": "immutable",
            "type-for-class-arg": "immutable: Optional[bool] = None",
            "required": False,
            "type": "bool",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "stringData",
            "name-for-class-arg": "string_data",
            "type-for-class-arg": "string_data: Optional[Dict[str, Any]] = None",
            "required": False,
            "type": "Dict[Any, Any]",
            "description": "<please add description>",
        },
        {
            "name-from-explain": "type",
            "name-for-class-arg": "type",
            "type-for-class-arg": 'type: Optional[str] = ""',
            "required": False,
            "type": "str",
            "description": "<please add description>",
        },
    ],
}
