name: Dummy pull_request_review workflow

on: pull_request_review

jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    name: dummy workflow
    steps:
      - name: Explanation
        run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"
