name: Label By comment
on: issue_comment

jobs:
  add_comment_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Label issue
        uses: myakove/set-labels@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}} # default token in GitHub Workflow
          action: labels_by_user_input
