name: Merge status label
on: status

jobs:
  merge_status_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge status label
        uses: myakove/pr-workflows@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          action: merge_status_label
