name: PR Actions
on: pull_request_target

jobs:
  initial_assignments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove Merge Checks
        uses: myakove/pr-workflows@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          action: remove_merge_checks

      - name: Assign Reviewers
        uses: myakove/pr-workflows@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          reviewers: myakove,rnetser
          action: add_reviewers

      - name: Assign Size Labels
        uses: myakove/pr-workflows@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          reviewers: myakove,rnetser
          action: size_label_prs
