name: Publish Python distributions to PyPI

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.sha }}
      - run: |
          python -m pip install build --user
          python -m build --sdist --outdir dist/

      #
      #      - name: Checkout version
      #        run: git checkout $GITHUB_SHA
      #
      #      - name: Install pypa/build
      #        run: >-
      #          python -m
      #          pip install
      #          build
      #          --user
      #
      #      - name: Build a binary wheel and a source tarball
      #        run: >-
      #          python -m
      #          build
      #          --sdist
      #          --outdir dist/
      #
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
