name: Pull Request Stats

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v2.14.0
        with:
          period: 7
          charts: true
          disableLinks: true
          sortBy: "COMMENTS"
