name: Upload Python distributions to PyPI

on:
  release:
    types: [created]

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.sha }}

      - name: Run Action
        uses: myakove/pr-workflows@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          action: upload_to_pypi
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
